name: NodeJS with TSC

on:
  push:
    branches: ['master', 'feature/*']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependancies
        run: npm install

      - name: Build TSC
        run: npm run tsc

      - name: Test & covers
        run: npm run coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@v1
