name: build

on:
  push:
    branches: ['master', 'feature/*']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build TSC
        run: npm run tsc

      - name: Cat store.d.ts
        run: cat dist/store.d.ts

      - name: Test & coverage
        run: npm run test:coverage

      - name: Coveralls publish on 24.x only
        if: matrix.node-version == '24.x'
        uses: coverallsapp/github-action@v2
